Matplotlib created a temporary config/cache directory at /tmp/matplotlib-r6wc1ku4 because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Error in <TFile::TFile>: file /tmp/LAB/histograms_Run04185.root does not exist
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cygno/__init__.py", line 80, in open_root
    f=ROOT.TFile.Open(fname)
  File "/usr/lib64/python3.6/site-packages/ROOT/pythonization/_tfile.py", line 67, in _TFileOpen
    raise OSError('Failed to open file {}'.format(str(args[0])))
OSError: Failed to open file /tmp/LAB/histograms_Run04185.root

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/condor/execute/dir_129/condor_exec.exe", line 290, in <module>
    cfile = cy.open_(runI[0], tag=tag, posix=False, verbose=False)
  File "/usr/local/lib/python3.6/site-packages/cygno/__init__.py", line 108, in open_
    f = open_root(run, path=path,  cloud=posix,  tag=tag, verbose=False)
  File "/usr/local/lib/python3.6/site-packages/cygno/__init__.py", line 88, in open_root
    raise myError("openFileError: "+fname)
cygno.myError: openFileError: /tmp/LAB/histograms_Run04185.root
